# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

# docs: https://espanso.org/docs/matches/basics/

matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  - trigger: ":now"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Y-%m-%d %H:%M"

  - trigger: ":blognow"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S %z"

  - trigger: ":blogpost"
    replace: "---\nlayout: blogpost.html\ntitle: new post\nslug: new-post\npermalink: /blog/new-post/\npublished_date: {{mydate}}\n---\n\n"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d %H:%M:%S %z"

# TODO: add extra filter like with tunic
  # - trigger: ".code"
  #   replace: "/banner from code {{paste}}\n/banner save "
  #   force_mode: keys
  #   vars:
  #     - name: "paste"
  #       type: clipboard

  # - trigger: ".put"
  #   replace: "<img src=\"{{url}}.png\" class=\"inline-banner\">"
  #   vars:
  #     - name: "url"
  #       type: shell
  #       params:
  #         # cmd: "string replace \"?writing=\" \"image/\" (paste)"
  #         # shell: fish
  #         # cmd: "pbpaste | str replace \"?writing=\" \"image/\""
  #         # shell: nu
  #         cmd: '/opt/homebrew/bin/fish -c "paste | sd \\\\?writing= image/ | sd .png\\|undefined/ \"\""'
  # - trigger: ".def"
  #   replace: "{{put}}:::"
  #   vars:
  #     - name: "put"
  #       type: match
  #       params:
  #         trigger: ".put"
