matches:
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  - trigger: ":time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  - trigger: ":now"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%Y-%m-%d %H:%M"

  - trigger: ":blognow"
    replace: "date: {{mydate}}\ntime: {{time}}\ntimezone: \"{{timezone}}\""
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
      - name: time
        type: date
        params:
          format: "%H:%M"
      - name: timezone
        type: date
        params:
          format: "%:::z"

  - trigger: ":blogpost"
    replace: "- title: post title\nslug: post-title\ndate: {{mydate}}\ntime: {{time}}\ntimezone: \"{{timezone}}\""
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
      - name: time
        type: date
        params:
          format: "%H:%M"
      - name: timezone
        type: date
        params:
          format: "%:::z"
